/* Generated By:JavaCC: Do not edit this line. LenguajesAutomatasConstants.java */
package clases;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LenguajesAutomatasConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CLASS = 6;
  /** RegularExpression Id. */
  int IF = 7;
  /** RegularExpression Id. */
  int TYPE = 8;
  /** RegularExpression Id. */
  int MODIFIER = 9;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 10;
  /** RegularExpression Id. */
  int BOOLEAN_LITERAL = 11;
  /** RegularExpression Id. */
  int IDENTIFIER = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"class\"",
    "\"if\"",
    "<TYPE>",
    "<MODIFIER>",
    "<INTEGER_LITERAL>",
    "<BOOLEAN_LITERAL>",
    "<IDENTIFIER>",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"==\"",
    "\"!=\"",
    "\"+\"",
    "\"-\"",
  };

}
